# Generated by Django 4.0.1 on 2022-03-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.URLField(default='google.com'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director_name',
            field=models.CharField(default='director name', max_length=70),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(default='movie name', max_length=70),
        ),
    ]
