# Generated by Django 4.0.1 on 2022-03-03 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0002_movie_poster_alter_movie_director_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(default='Username', max_length=70)),
                ('comment_in_english', models.CharField(max_length=700)),
                ('comment_in_german', models.CharField(max_length=700)),
                ('comment_in_french', models.CharField(max_length=700)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviesapp.movie')),
            ],
        ),
    ]
